### ISSUE TITLE
Frontend: Receive Backend Messages

### ISSUE THREAD

**Issue by gsubram4** [gsubram4/covert_tuba#4]
Frontend should receive messages from the backend and present it to users. 

Please suggest preferred API...

**Comment by gsubram4** [comment]
I think we want 2 types of messages to start with
* Normal (Green)
* Error (Red)

**Comment by enayetn** [comment]
UI will now respond to events "send_notification"

Expects object with following structure
```
{
   message: {string}
   theme: {string} one of:  success, secondary, failure, warning, bland, blandpop -- default 'success'
   duration: {int} ms for message duration -- default 2000
}
```
